routes/admin.php
<?php


Auth::routes();
Route::group(['middleware' => 'auth'], function (){
Route::get('/','Admin\IndexController@index')->name('admin.index');
Route::resource('/menu', 'Admin\MenuController');
Route::resource('/price', 'Admin\PriceController');
Route::resource('/slider', 'Admin\SliderController');
Route::resource('/category', 'Admin\CategoryController');
Route::resource('/product', 'Admin\ProductController');
Route::resource('/page', 'Admin\PageController');
Route::resource('/order','Admin\OrderController');
Route::get('/sortNew','Admin\SortController@sortNew')->name('sortNew');
Route::get('/sortAssecc','Admin\SortController@sortAssecc')->name('sortAssecc');
});

routes/web.php
<?php

Route::get('/','Site\IndexController@index');

Route::get('category', 'Site\ProductCategory@index')->name('site.category.index');
Route::get('category/{id}', 'Site\ProductCategory@show')->name('site.category.show');

Route::get('product', 'Site\ProductController@index')->name('site.product.index');
Route::post('product', 'Site\ProductController@addToCart')->name('site.product.cart');
Route::get('product/{product}','Site\ProductController@getShowProduct')->name('site.product.show');

Route::get('/cart/order','Site\OrderController@index')->name('firstStepOrder');
Route::post('/cart/order/complete','Site\OrderController@store')->name('storeStepOrder');
Route::get('cart','Site\CartController@index')->name('cart');
Route::post('cart','Site\CartController@remove')->name('cartRemove');
Route::post('/cart/update','Site\CartController@update')->name('cartUpdate');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/{url}', 'Site\PageController@index')->name('site.page.index');

Route::get('/public/{price}', 'Site\PriceController@download')->name('site.price.download');

resources/views/admin/app.blade.php
<!-- UIkit CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.17/css/uikit.min.css" />
	<link rel="stylesheet" href="css/style.css" />
  <link rel="stylesheet" href="css/uikit.min.css" />

<!-- UIkit JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.17/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.17/js/uikit-icons.min.js"></script>

@include ('admin.message.index')

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>UI Admin - Clean and responsive administration panel</title>

        <meta charset="UTF-8">
        <meta name="description" content="Clean and responsive administration panel">
        <meta name="keywords" content="Admin,Panel,HTML,CSS,XML,JavaScript">
        <meta name="author" content="Erik Campobadal">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="css/uikit.min.css" />

		    <link rel="stylesheet" href="css/style.css" />

         <script src="js/uikit.min.js" ></script>
		     <script src="js/uikit-icons.min.js" ></script>
    </head>
    <body>

      @include ('admin.top_menu')

        <div class=" content-background">
            <div class="uk-section-small uk-section-default header">
                <div class="uk-container uk-container-large">
                    <h1><span class="ion-speedometer"></span> Dashboard</h1>
                    <p>
                        Добро пожаловать в админ панель 2F
                    </p>

                </div>
            </div>
            <div class="uk-section-small">
                <div class="uk-container uk-container-large">
                    <div uk-grid class="uk-child-width-1-1@s uk-child-width-1-2@m uk-child-width-1-4@xl">
                        <div>
                            <div class="uk-card uk-card-default uk-card-body">
                                <span class="statistics-text">Новые Заказы</span><br />
                                <span class="statistics-number">
                                  <a href="{{route('order.index')}}">{{$orders->where('status',0)->count()}}</a>
                                    <span class="uk-label uk-label-success">
                                        8% <span class="ion-arrow-up-c"></span>
                                    </span>
                                </span>
                            </div>
                        </div>
                        <div>
                            <div class="uk-card uk-card-default uk-card-body">
                                <span class="statistics-text">Товары</span><br />
                                <span class="statistics-number">
                                    {{$products->count()}}
                                    <span class="uk-label uk-label-danger">
                                        13% <span class="ion-arrow-down-c"></span>
                                    </span>
                                </span>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
		<!-- Load More Javascript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js" integrity="sha256-UGwvyUFH6Qqn0PSyQVw4q3vIX0wV1miKTracNJzAWPc=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.transit/0.9.12/jquery.transit.min.js" integrity="sha256-rqEXy4JTnKZom8mLVQpvni3QHbynfjPmPxQVsPZgmJY=" crossorigin="anonymous"></script>
		<script src="js/notyf.min.js"></script>
		<!-- Required Overall Script -->
        <script src="js/script.js"></script>
		<!-- Status Updater -->
		<script src="js/status.js"></script>
		<!-- Sample Charts -->
		<script src="js/charts.js"></script>
		<!-- Sample Notifications -->
		<script src="js/notification.js"></script>
    </body>
</html>

resources/views/admin/top_menu.blade.php
<nav class="uk-navbar-container" style="background:#1e87f0;" uk-navbar>
  <div class="uk-navbar-left">
      <ul class="uk-navbar-nav ">
        <li>

          <a href="{{route('admin.index')}}" style="color:#fff;"  class="uk-icon-link" href="admin" >  <span uk-icon="icon: uikit;ratio: 2;" ></span></a>
        </li>
          <li>
             <a style="color:#fff;"  class="uk-icon-link" href="{{route('order.index')}}" >    <span uk-icon="icon: bell"   style="margin-right: 5px;"></span> Заказы
               <span class="uk-label uk-label-success" style="margin-left: 5px;">
               {{$orders->where('status',0)->count()}}
              </span>
            </a>
          </li>

          <li>
             <a style="color:#fff;"  class="uk-icon-link" href="{{route('product.index')}}" >  <span uk-icon="icon: grid" style="margin-right: 5px;"></span>Товары</a>
          </li>

          <li>
             <a style="color:#fff;"  class="uk-icon-link" href="{{route('menu.index')}}" >    <span uk-icon="icon: menu" style="margin-right: 5px;"></span>Меню сайта</a>
          </li>

          <li>
             <a style="color:#fff;"  class="uk-icon-link" href="{{route('price.index')}}" >    <span uk-icon="icon: file" style="margin-right: 5px;"></span>Прайс лист</a>
          </li>

          <li>
             <a style="color:#fff;"  class="uk-icon-link" href="{{route('category.index')}}"> <span uk-icon="icon: hashtag" style="margin-right: 5px;"></span>Категории</a>
          </li>

          <li>
             <a style="color:#fff;"  class="uk-icon-link" href="{{route('slider.index')}}"> <span uk-icon="icon: image" style="margin-right: 5px;"></span>Слайдеры</a>
          </li>

          <li>
             <a style="color:#fff;"  class="uk-icon-link" href="{{route('page.index')}}" > <span uk-icon="icon: info" style="margin-right: 5px;"></span>Инфо страницы</a>
          </li>
          <li>
            <div class="uk-button uk-button-default uk=padding-small" style="color:#fff;align:right;margin-top:18px;font-weight:bold;">
              @if (\Route::current()->getName() == 'order.index')
              <a  href="{{route('order.create')}}" class="uk-link-reset">Добавить заказ</a>

              @elseif (\Route::current()->getName() == 'product.index')
              <a  href="{{route('product.create')}}" class="uk-link-reset">Добавить товар</a>

              @elseif (\Route::current()->getName() == 'menu.index')
              <a  href="{{route('menu.create')}}" class="uk-link-reset">Добавить пункт меню</a>

              @elseif (\Route::current()->getName() == 'price.index')
              <a  href="{{route('price.create')}}" class="uk-link-reset">Обновить прайс</a>

              @elseif (\Route::current()->getName() == 'category.index')
              <a  href="{{route('category.create')}}" class="uk-link-reset">Добавить категорию</a>

              @elseif (\Route::current()->getName() == 'slider.index')
              <a  href="{{route('slider.create')}}" class="uk-link-reset">Добавить слайдер</a>

              @elseif (\Route::current()->getName() == 'page.index')
              <a  href="{{route('page.create')}}" class="uk-link-reset">Добавить инфо страницу</a>

              @else

                
              @endif
            </div>
          </li>

      </ul>

  </div>
</nav>

resources/views/admin/validation.blade.php
<!-- Scripts -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>

<!-- Laravel Javascript Validation -->
<script type="text/javascript" src="{{ url('vendor/jsvalidation/js/jsvalidation.js')}}"></script>